### ISSUE TITLE
port 443 vs 8080

### ISSUE THREAD

**Issue by marcvs** [dianagudu/mccli#1]
mccli should first try 443. If that is not available, (e.g. because the server didn't install a certificate yet) it should
- try 8080
- issue a warning that encryption is not working yet
- ask the user to continue
- continue using 8080

**Comment by dianagudu** [comment]
fix pushed to master, with some differences from suggestion above:
* try 443 first (if available, but certificate invalid, e.g. self signed, suggest --ignore to skip certificate verification, and exit; strongly advise against --ignore, and issue warning when this is used)
* if not available, try 8080
* if 8080 available, issue warning and continue with it (asking the user to confirm every time might get annoying)
* if not available, ask user to specify --mc-endpoint and exit
